apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.7.8
    helm:
      values: |
        server:
          service:
            type: LoadBalancer
          config:
            url: https://argocd.192-168-122-70.nip.io
          ingress:
            enabled: true
            hosts:
              - argocd.192-168-122-70.nip.io
            tls:
              - secretName: argocd-server-tls
                hosts:
                  - argocd.192-168-122-70.nip.io
        configs:
          params:
            server.insecure: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
