apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: openstack
  namespace: argocd
spec:
  description: OpenStack deployment project
  sourceRepos:
  - '*'
  destinations:
  - namespace: openstack
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  - group: 'apiextensions.k8s.io'
    kind: CustomResourceDefinition
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
